name: NoForget
options:
  bundleIdPrefix: com.noforget
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  NoForget:
    type: application
    platform: iOS
    sources:
      - path: NoForget
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noforget.app
        INFOPLIST_FILE: NoForget/Info.plist
        CODE_SIGN_ENTITLEMENTS: NoForget/NoForget.entitlements
        SUPPORTS_MACCATALYST: true
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "-"

  NoForgetWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: NoForgetWidget
        excludes:
          - "**/.DS_Store"
      - path: NoForget/Models/ReminderAttributes.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noforget.app.widget
        SKIP_INSTALL: true
        TARGETED_DEVICE_FAMILY: "1,2"
